services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    restart: unless-stopped
    profiles:
      - prod
      - dev
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: rightbite
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
    ports:
      - '5432:5432'
    tmpfs:
      - /var/lib/postgresql/data
    profiles:
      - dev
