#30 min
accessTokenAvailableValidityPeriodInSec: 1800
#30 days
refreshTokenAvailableValidityPeriodInSec: 2592000

spring:
  application:
    name: right-bite
  profiles:
    active: dev
  docker:
    compose:
      lifecycle-management: start_and_stop
      enabled: false #i've turned up it to false to resolve all problem with docker
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: "https://api.groq.com/openai"
      chat:
        options:
          model: "llama3-70b-8192"
server:
  port: 8080

