jwt.secret.key: f8G7YxZ2KmL9QaP5RsDcVb3WNeJh4Tu1
spring:
  application:
    name: right-bite
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    username: h2
    password: h2
    url: jdbc:h2:mem:h2db;
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console