jwt.secret.key: f8G7YxZ2KmL9QaP5RsDcVb3WNeJh4Tu1
spring:
  application:
    name: right-bite
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    username: h2
    password: h2
    url: jdbc:h2:mem:h2db
  jpa:
    hibernate:
      ddl-auto: none #create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: never
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: INFO               # Основной уровень логирования
    com.bestStore: DEBUG     # Включаем DEBUG для своего кода
    org.springframework.web: WARN
    org.hibernate.SQL: DEBUG        # SQL запросы (если нужно)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Значения параметров (если нужно)
    org.flywaydb.core: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
