jwt.secret.key: f8G7YxZ2KmL9QaP5RsDcVb3WNeJh4Tu1
spring:
  application:
    name: right-bite
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    username: h2
    password: h2
    url: jdbc:h2:mem:h2db;
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  security:
    oauth2:
      client:
        registration:
          google:

            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
  mail:
    host: smtp.gmail.com
    port: 587
    username: i.murashko0911@gmail.com
    password: bngf mhxr xxvp sisb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: DEBUG # всё приложение в режиме DEBUG
    org.springframework: INFO # можно оставить INFO, иначе много шума
    org.springframework.boot.autoconfigure: INFO # покажет, какие автоконфигурации включаются
    org.springframework.data.redis: DEBUG # Redis-соединения
    io.lettuce.core: WARN # понижаем шум от клиента Redis (или DEBUG, если нужно)
    com.bestStore: DEBUG # твой код
    sun: info
    javax.management: info
    com.zaxxer: info