tokens:
  #30 min
  accessTokenAvailableValidityPeriodInSec: 1800
  #30 days
  refreshTokenAvailableValidityPeriodInSec: 2592000
spring:
  application:
    name: right-bite
  cache:
    type: caffeine

  ai:
    openai:
      api-key: ${API_KEY}
      base-url: ${BASE_URL}
      chat:
        options:
          model: ${API_MODEL}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8080
