jwt.secret.key: ${JWT_SECRET_KEY}
spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: INFO               # Основной уровень логирования
    com.best_store: DEBUG     # Включаем DEBUG для своего кода
    org.springframework.web: WARN
    org.hibernate.SQL: DEBUG        # SQL запросы (если нужно)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Значения параметров (если нужно)
    org.flywaydb.core: DEBUG

