tokens:
  #30 min
  accessTokenAvailableValidityPeriodInSec: 1800
  #30 days
  refreshTokenAvailableValidityPeriodInSec: 2592000

spring:
  profiles:
    active: dev
  application:
    name: right-bite
#  profiles:
#    active: dev
  ai:
    openai:
      api-key: ${API_KEY}
      base-url: ${BASE_URL}
      chat:
        options:
          model: ${API_MODEL}

server:
  port: 8080
