jwt.secret.key: f8G7YxZ2KmL9QaP5RsDcVb3WNeJh4Tu1
spring:
  application:
    name: right-bite
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true