tokens:
  #30 min
  accessTokenAvailableValidityPeriodInSec: 1800
  #30 days
  refreshTokenAvailableValidityPeriodInSec: 2592000
spring:
#  profiles:
#    active: dev

  application:
    name: right-bite
  cache:
    type: caffeine
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

server:
  port: 8080
