tokens:
  #30 min
  accessTokenAvailableValidityPeriodInSec: 1800
  #30 days
  refreshTokenAvailableValidityPeriodInSec: 2592000

spring:
  application:
    name: right-bite
  profiles:
    active: dev
  docker:
    compose:
      lifecycle-management: start_and_stop
      enabled: true
server:
  port: 8080
