jwt.secret.key: f8G7YxZ2KmL9QaP5RsDcVb3WNeJh4Tu1
spring:
  application:
    name: right-bite
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    username: ${DB_USERNAME}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      enabled: true
      