jwt:
  secret:
    access: hBkhevRQ2pgxN1TFpQetX9fgpeNC5sEQU
    refresh: hBkhevRQ2pgxN1TFpQetX9fgpeNC5sEQU
auth:
  redirect:
    default-url: dummy
    session-attribute-name: oauth2_redirect_uri
spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    username: h2
    password: h2
    url: jdbc:h2:mem:h2db;
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      highlight_sql: true
      use_sql_comments: true
  flyway:
    locations: classpath:db/migration
    enabled: false
    baseline-on-migrate: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dummy
            client-secret: dummy
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
  mail:
    host: dummy
    port: 123
    username: dummy
    password: dummy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      profiles:
        active: test
  ai:
    openai:
      api-key: dummy
      base-url: dummy
      chat:
        options:
          model: dummy
