jwt.secret.key: ${JWT_SECRET_KEY}
spring:
#  config:
#    activate:
#      on-profile: prod
#    import: optional:file:.env[.properties]
  data:
    redis:
      url: ${REDIS_URL}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      highlight_sql: true
      use_sql_comments: true
  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      profiles:
        active: prod
  ai:
    openai:
      api-key: ${API_KEY}
      base-url: ${BASE_URL}
      chat:
        options:
          model: ${API_MODEL}
logging:
  level:
    root: INFO               # Основной уровень логирования
    com.best_store: DEBUG     # Включаем DEBUG для своего кода
    org.springframework.web: WARN
    org.hibernate.SQL: DEBUG        # SQL запросы (если нужно)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Значения параметров (если нужно)
    org.flywaydb.core: DEBUG

